#! /bin/sh

cd /etc/openvpn
CONFIGS=`ls *.ovpn 2>/dev/null`
if [[ "$?" == "1" ]]; then
  echo "No OpenVPN configurations found in /etc/openvpn"
  exit 1
fi

trap "kill -TERM -1" KILL TERM INT
for config in $CONFIGS; do
  always openvpn --config $config &
done
wait
