#! /bin/sh

VERSION=2.7.17

set -e
apk-begin .builddeps \
  autoconf \
  coreutils \
  make \
  gcc \
  linux-headers \
  pkgconf \
  musl-dev \
  db-dev \
  ncurses-dev \
  openssl-dev \
  tcl-dev \
  tk-dev \
  bzip2-dev \
  gdbm-dev \
  readline-dev

get-source python https://www.python.org/ftp/python/${VERSION}/Python-${VERSION}.tar.xz
build-package python build
mkdir -p /usr/local/include
cp -R /usr/src/build/usr/local/include/python2.7 /usr/local/include/python2.7
strip-build build
install-build build
rm -rf /usr/src/python
cd /usr/src
curl -L -s https://bootstrap.pypa.io/get-pip.py | python -

apk-end .builddeps
