#! /bin/sh

rm -rf /init/configs

cd /etc/openvpn
CONFIGS=`ls *.ovpn | sed -E -e s/\.ovpn// 2>/dev/null`

for config in $CONFIGS; do
  mkdir -p /init/configs/$config
  echo "#! /bin/sh" > /init/configs/$config/run
  echo "cd /etc/openvpn" >> /init/configs/$config/run
  echo "exec openvpn --config ${config}.ovpn" >> /init/configs/$config/run
  chmod 755 /init/configs/$config/run
done
