#! /bin/sh

if [ -f "/init/environment" ]; then
  . /init/environment
fi

if [ -f "/init/startup" ]; then
  /init/startup
fi

trap "kill -TERM -1" KILL TERM INT
runsvdir /init/services &
wait

sv down `ls /init/services`

if [ -f "/init/shutdown" ]; then
  /init/shutdown
fi
